services:
  postgres:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mock_db
      SSL_MODE: disable
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: